"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SocialAuthButtons = exports.FacebookButton = exports.TwitterButton = exports.AppleButton = exports.GoogleButton = exports.forgotPasswordValidationSchema = exports.registrationValidationSchema = exports.loginValidationSchema = exports.passwordSchema = exports.emailSchema = exports.handleAuthError = exports.formatAuthError = exports.getFirebaseApp = exports.getFirebaseAuth = exports.initializeFirebase = exports.useAuth = exports.AuthProvider = void 0;
// Export all components and utilities
var useAuth_1 = require("./hooks/useAuth");
Object.defineProperty(exports, "AuthProvider", { enumerable: true, get: function () { return useAuth_1.AuthProvider; } });
Object.defineProperty(exports, "useAuth", { enumerable: true, get: function () { return useAuth_1.useAuth; } });
var config_1 = require("./firebase/config");
Object.defineProperty(exports, "initializeFirebase", { enumerable: true, get: function () { return config_1.initializeFirebase; } });
Object.defineProperty(exports, "getFirebaseAuth", { enumerable: true, get: function () { return config_1.getFirebaseAuth; } });
Object.defineProperty(exports, "getFirebaseApp", { enumerable: true, get: function () { return config_1.getFirebaseApp; } });
var errors_1 = require("./utils/errors");
Object.defineProperty(exports, "formatAuthError", { enumerable: true, get: function () { return errors_1.formatAuthError; } });
Object.defineProperty(exports, "handleAuthError", { enumerable: true, get: function () { return errors_1.handleAuthError; } });
var validation_1 = require("./utils/validation");
Object.defineProperty(exports, "emailSchema", { enumerable: true, get: function () { return validation_1.emailSchema; } });
Object.defineProperty(exports, "passwordSchema", { enumerable: true, get: function () { return validation_1.passwordSchema; } });
Object.defineProperty(exports, "loginValidationSchema", { enumerable: true, get: function () { return validation_1.loginValidationSchema; } });
Object.defineProperty(exports, "registrationValidationSchema", { enumerable: true, get: function () { return validation_1.registrationValidationSchema; } });
Object.defineProperty(exports, "forgotPasswordValidationSchema", { enumerable: true, get: function () { return validation_1.forgotPasswordValidationSchema; } });
var SocialAuthButtons_1 = require("./components/SocialAuthButtons");
Object.defineProperty(exports, "GoogleButton", { enumerable: true, get: function () { return SocialAuthButtons_1.GoogleButton; } });
Object.defineProperty(exports, "AppleButton", { enumerable: true, get: function () { return SocialAuthButtons_1.AppleButton; } });
Object.defineProperty(exports, "TwitterButton", { enumerable: true, get: function () { return SocialAuthButtons_1.TwitterButton; } });
Object.defineProperty(exports, "FacebookButton", { enumerable: true, get: function () { return SocialAuthButtons_1.FacebookButton; } });
Object.defineProperty(exports, "SocialAuthButtons", { enumerable: true, get: function () { return SocialAuthButtons_1.SocialAuthButtons; } });
